version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Building SAM application..."
      - sam build --template-file backend/template.yaml
  build:
    commands:
      - echo "Deploying SAM stack..."
      - |
        sam deploy \
          --stack-name case-timeline-organizer-dev \
          --template-file .aws-sam/build/template.yaml \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset \
          --resolve-s3 \
          --region $AWS_DEFAULT_REGION
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
